function logvars(logfile, nrOutputs, amplitude, frequency, stimdur_on, stimdur_off, stimdur_total, restdur, pTime, reps)
% Used for logging the parameters of each experiment. 

if nargin < 8
    fprintf(logfile, '\n%s: %f\n%s: %f\n%s: %f\n%s: %f\n%s: %f\n%s: %f\n\n',...
        'number of outputs: ', nrOutputs,...
        'amplitude: ', amplitude, ...
        'frequency: ', frequency, ...
        'duration of stimulation ON in seconds: ', stimdur_on, ...
        'duration of stimulation OFF in seconds: ', stimdur_off, ...
        'total stimulation duration: ', stimdur_total);
else
    fprintf(logfile, '\n%s: %f\n%s: %f\n%s: %f\n%s: %f\n%s: %f\n%s: %f\n%s: %f\n%s: %f\n%s: %f\n\n',...
        'number of outputs: ', nrOutputs,...
        'amplitude: ', amplitude, ...
        'frequency: ', frequency, ...
        'duration of stimulation ON in seconds: ', stimdur_on, ...
        'duration of stimulation OFF in seconds: ', stimdur_off, ...
        'duration between blocks in seconds: ', restdur,...
        'duration between stimulation in seconds: ', pTime,...
        'total stimulation duration: ', stimdur_total, ... 
        'number of repetitions: ', reps);
end
end
